#! /bin/bash

# File: /etc/init.d/unicorn

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
# Description:       starts unicorn
### END INIT INFO

source /usr/local/rvm/scripts/rvm
DAEMON=unicorn
#DAEMON_OPTS="-c /usr/local/src/ubiQube/config/unicorn.rb -D"
#DAEMON_OPTS="-c /usr/local/src/test/rubycas-client/config/unicorn.rb -D"
DAEMON_OPTS="-c /usr/local/src/ubiQube/rails/config/unicorn.rb -D"
#PID=/usr/local/src/ubiQube/shared/pids/unicorn.pid
#PID=/usr/local/src/test/rubycas-client/shared/pids/unicorn.pid
PID=/usr/local/src/ubiQube/rails/shared/pids/unicorn.pid
NAME=unicorn
DESC="Unicorn app for testapp"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
        kill -QUIT `cat $PID`
    sleep 1
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
    ;;
  reload)
        echo -n "Reloading $DESC configuration: "
        kill -HUP `cat $PID`
        echo "$NAME."
        ;;
  *)
    echo "Usage: $NAME {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
